apiVersion: v1
kind: Service
metadata:
  name: smoke-nginx
  namespace: telecom
  labels:
    app: smoke-nginx
spec:
  selector:
    app: smoke-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
