apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-nginx
  namespace: telecom
  labels:
    app: smoke-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoke-nginx
  template:
    metadata:
      labels:
        app: smoke-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          imagePullPolicy: IfNotPresent
