apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: telecom
data:
  smf.yaml: |
    logger:
      file:
        path: /dev/stdout

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777

      pfcp:
        server:
          - address: 0.0.0.0
        client:
          upf:
            - address: 172.21.70.46

      gtpc:
        server:
          - address: 0.0.0.0

      gtpu:
        server:
          - address: 0.0.0.0

      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet

      dns:
        - 8.8.8.8
        - 8.8.4.4

      mtu: 1400
