apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: telecom
data:
  smf.yaml: |
    logger:
      file:
        path: /dev/stdout

    global:
      max:
        ue: 1024

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          scp:
            - uri: http://open5gs-scp:7777

      pfcp:
        server:
          - address: 0.0.0.0

      gtpc:
        server:
          - address: 0.0.0.0

      gtpu:
        server:
          - address: 0.0.0.0

      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet

      dns:
        - 8.8.8.8
        - 1.1.1.1
