apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-upf
  namespace: telecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-upf
  template:
    metadata:
      labels:
        app: open5gs-upf
    spec:
      containers:
        - name: upf
          image: docker.io/gradiant/open5gs:2.7.6
          command: ["/bin/sh", "-c"]
          args:
            - open5gs-upfd -c /etc/open5gs/upf.yaml
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8805
              protocol: UDP
            - containerPort: 2152
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/upf.yaml
              subPath: upf.yaml
            - name: dev-net-tun
              mountPath: /dev/net/tun
      volumes:
        - name: config
          configMap:
            name: open5gs-upf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
