apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: telecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-nrf
  template:
    metadata:
      labels:
        app: open5gs-nrf
    spec:
      containers:
        - name: nrf
          image: docker.io/gradiant/open5gs:2.7.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - >
              open5gs-nrfd -c /etc/open5gs/nrf.yaml
          ports:
            - name: sbi
              containerPort: 7777
              protocol: TCP
          volumeMounts:
            - name: nrf-config
              mountPath: /etc/open5gs/nrf.yaml
              subPath: nrf.yaml
          readinessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: nrf-config
          configMap:
            name: open5gs-nrf-config
