apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  namespace: telecom
spec:
  selector:
    app: open5gs-nrf
  ports:
    - name: sbi
      port: 7777
      targetPort: 7777
      protocol: TCP
  type: ClusterIP
