apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: telecom
spec:
  type: NodePort
  selector:
    app: open5gs-webui
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
